### ISSUE TITLE
Installation issue api login

### ISSUE THREAD

**Issue by ghost** [shadowcodex/c9.ide.desktop#1]
Hi, 
when I run "c9 install c9.ide.desktop" in a new terminal, I get asked to give my username and pw for "https://api.c9.io/user" I think. However, when I fill in my login info, it asks again. Do you know what's up with that ?

Thanks

**Comment by shadowcodex** [comment]
It asks for the username and password that you log into https://c9.io with. So just your regular c9 Username and Password.

If it isn't working for you with those credentials then you will need to file an issue with c9 at their support email 'support@c9.io'
