### ISSUE TITLE
Won't Let Me Install

### ISSUE THREAD

**Issue by CrispyBacon1999** [shadowcodex/c9.ide.desktop#10]
When I try to install this through the terminal, it gives me an error

> module.js:327
>     throw err;
>     ^
> 
> Error: Cannot find module 'npmlog'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at /mnt/shared/sbin/npm:18:11
>     at Object.<anonymous> (/mnt/shared/sbin/npm:75:3)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
> Command failed: /mnt/shared/sbin/npm.

**Comment by shadowcodex** [comment]
Please post your concerns here in this thread: https://community.c9.io/t/cannot-find-module-npmlog-when-trying-to-install-scala-plugin-for-cloud9/6846/6

This is a current bug in cloud9's plugin system. It affects all plugins.
