### ISSUE TITLE
Question: Can this desktop be accessed from outside?

### ISSUE THREAD

**Issue by jenishngl** [shadowcodex/c9.ide.desktop#11]
Can I access this desktop from an online vnc viewer like http://kanaka.github.io/noVNC/noVNC/vnc.html?

If yes, then how do I do it?

**Comment by shadowcodex** [comment]
Yes, use a url like this: https://$C9_HOSTNAME/vnc.html

I believe it is something like https://user-project.c9users.io/vnc.html/

It should be accessible once the vnc session is started. If you can access it in the IDE then that link should be accessible outside the IDE too.

**Comment by jenishngl** [comment]
Yeah it worked. Thanks
