### ISSUE TITLE
Delay in desktop starting ability?

### ISSUE THREAD

**Issue by MrLoudlyspell** [shadowcodex/c9.ide.desktop#12]
So i decided to leave my cloud 9 alone for about 10 minutes, and then when i reloaded the page, i went to "view" at the top, and my "start/open desktop" options were gone. After looking through the solved issues page, I looked back and it was there. Does this mean that there is a small delay from when you open the cloud 9, to when the desktop is actually available to run?

**Comment by shadowcodex** [comment]
It should happen instantly.

**Comment by MrLoudlyspell** [comment]
Alright. Thanks so much for creating this page :). It is starting to work perfectly for me now.

**Comment by shadowcodex** [comment]
Awesome! Glad it is going good for you!
