### ISSUE TITLE
Desktop cursor not working

### ISSUE THREAD

**Issue by shloak** [shadowcodex/c9.ide.desktop#3]
I am able to get the desktop up and running; however, my cursor does not work on the desktop. The cursor immediately disappears as I go from the blue toolbar to the black desktop and I cannot right click anywhere on the desktop to bring up the application menu.I am able to toggle the blue buttons on the toolbar, but I cannot do anything on the desktop.

**Comment by shadowcodex** [comment]
This plugin relies on noVNC [https://github.com/kanaka/noVNC](https://github.com/kanaka/noVNC)

The issue with the cursor should be reported there.

**Comment by kmishra9** [comment]
Lol now this is an issue for me... Fix one problem, find another? I'll report it to noVNC as well.

UPDATE: fixed the original issue of this thread in the GitHub link below. Another problem has come up for me, but at least you'll be able to see the cursor now

**Comment by shadowcodex** [comment]
Man that's funky for sure. I'm not really sure why. Varied browser support from noVNC I'd guess.

**Comment by kmishra9** [comment]
That's what I thought until it worked on Chrome on my Chromebook and on my friend's chrome browser as well. Oh well lol, I guess I'll have a browser somewhere always dedicated to graphical cloud9 for my classes

**Comment by shadowcodex** [comment]
Well thats good I guess?
