### ISSUE TITLE
Cannot find module 'npmlog'

### ISSUE THREAD

**Issue by antogerva** [shadowcodex/c9.ide.desktop#7]
Before, I had no trouble installing c9.ide.desktop on an ubuntu system, but recently I went ahead and installed c9.ide.desktop into a new ubuntu system and got the following error:
(note: I already activated `Load Plugins From Workspace` and `Load Custom Plugins`)

```
antogerva:~ $ c9 install c9.ide.desktop --force
module.js:327
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /mnt/shared/sbin/npm:18:11
    at Object.<anonymous> (/mnt/shared/sbin/npm:75:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
Command failed: /mnt/shared/sbin/npm
```

**Comment by dbz2k** [comment]
I also have this error :(

**Comment by shadowcodex** [comment]
try `npm install -g npmlog`?

Then try to install the plugin. Is this on c9.io workspace or an ssh workspace?

**Comment by antogerva** [comment]
It's on a c9.io workspace. Look like c9 use `/mnt/shared/sbin/npm` when installing plugin. Maybe the npm installation is broken, since I get the same npmlog error when calling:

```
/mnt/shared/sbin/npm -v
```

Also, this npm executable seem to be mounted in a read-only drive(and sudo won't help).

That being said, look like this isn't an issue with this plugin in particular:
https://community.c9.io/t/cannot-find-module-npmlog-when-trying-to-install-scala-plugin-for-cloud9/6846

**Comment by shadowcodex** [comment]
Ah yeah, it seems like a c9 issue. I'm going to move the conversation over to the c9 community forum. Closing this issue. If you have any other problems besides this particular one let me know!
