### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by kmishra9** [shadowcodex/c9.ide.desktop#9]
Hi,

I (and correspondingly my students) seem to have a problem installing 
![screenshot_2016-07-23_00-58-31](https://cloud.githubusercontent.com/assets/10662252/17076801/ae84cb80-5070-11e6-9eb8-7a01ad7d8580.png)

This is the bash file I'm running:

```
#!/bin/bash

echo "Beginning setup of your Cloud 9 Workspace"


echo ""
echo "Installing pip, Python3's package manager"
sudo easy_install3 pip

echo ""
echo "Installing getch"
sudo python3 -m pip install getch

echo ""
echo "Installing termcolor"
sudo python3 -m pip install termcolor

echo ""
echo "Installing websockify"
sudo apt-get install websockify

echo ""
echo "Installing C9 Desktop"
c9 install c9.ide.desktop --force

echo ""
echo "Setting permissions"
chmod a-wx Resources.txt
```

**Comment by Semior001** [comment]
Run command: 
`sudo pip3 install npm`
and try again

**Comment by shadowcodex** [comment]
This is a known issue with c9's plugin system. They are working on a fix for it.

Check this thread for updates: 
https://community.c9.io/t/cannot-find-module-npmlog-when-trying-to-install-scala-plugin-for-cloud9/6846/8

It affects all plugins.
